[2023-12-24T14:56:37.096+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: elastic_dag.print_es_info manual__2023-12-24T14:56:35.829169+00:00 [queued]>
[2023-12-24T14:56:37.101+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: elastic_dag.print_es_info manual__2023-12-24T14:56:35.829169+00:00 [queued]>
[2023-12-24T14:56:37.102+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-24T14:56:37.102+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-24T14:56:37.102+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-24T14:56:37.109+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): print_es_info> on 2023-12-24 14:56:35.829169+00:00
[2023-12-24T14:56:37.112+0000] {standard_task_runner.py:55} INFO - Started process 689 to run task
[2023-12-24T14:56:37.114+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'elastic_dag', 'print_es_info', 'manual__2023-12-24T14:56:35.829169+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/elastic_dag.py', '--cfg-path', '/tmp/tmp7zh8f23b']
[2023-12-24T14:56:37.116+0000] {standard_task_runner.py:83} INFO - Job 185: Subtask print_es_info
[2023-12-24T14:56:37.148+0000] {task_command.py:376} INFO - Running <TaskInstance: elastic_dag.print_es_info manual__2023-12-24T14:56:35.829169+00:00 [running]> on host b5bd61ab1ebf
[2023-12-24T14:56:37.183+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=elastic_dag
AIRFLOW_CTX_TASK_ID=print_es_info
AIRFLOW_CTX_EXECUTION_DATE=2023-12-24T14:56:35.829169+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-24T14:56:35.829169+00:00
[2023-12-24T14:56:37.193+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/elastic_dag.py", line 8, in _print_es_info
    hook = ElasticHook()
  File "/opt/airflow/plugins/hooks/elastic/elastic_hook.py", line 10, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `elastic_default` isn't defined
[2023-12-24T14:56:37.197+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=elastic_dag, task_id=print_es_info, execution_date=20231224T145635, start_date=20231224T145637, end_date=20231224T145637
[2023-12-24T14:56:37.202+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 185 for task print_es_info (The conn_id `elastic_default` isn't defined; 689)
[2023-12-24T14:56:37.208+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-24T14:56:37.220+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
